package com.voidlab.player.ui.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.voidlab.player.audio.playback.PlaybackManager
import com.voidlab.player.data.models.EQPreset
import com.voidlab.player.data.models.EQProfile
import com.voidlab.player.data.repository.EQRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import javax.inject.Inject

@HiltViewModel
class EQViewModel @Inject constructor(
    private val eqRepository: EQRepository,
    private val playbackManager: PlaybackManager
) : ViewModel() {
    
    val allProfiles: StateFlow<List<EQProfile>> = eqRepository.getAllProfiles()
        .stateIn(viewModelScope, SharingStarted.Lazily, emptyList())
    
    val currentSong = playbackManager.currentSong
    val isAutoEQEnabled = playbackManager.isAutoEQEnabled
    val isLearning = playbackManager.isLearning
    val learningProgress = playbackManager.learningProgress
    
    fun toggleAutoEQ(enabled: Boolean) {
        playbackManager.toggleAutoEQ(enabled)
    }
    
    fun applyPreset(preset: EQPreset) {
        // TODO: Apply preset through PlaybackManager/EqualizerEngine
        viewModelScope.launch {
            val song = currentSong.value ?: return@launch
            val profile = EQProfile.fromBandValues(
                song.id, song.title, song.artist,
                preset.bandValues,
                isAutoGenerated = false,
                learningProgress = 100f
            )
            eqRepository.saveProfile(profile)
        }
    }
    
    fun updateBandLevel(bandIndex: Int, value: Float) {
        // TODO: Update through PlaybackManager/EqualizerEngine
    }
    
    fun deleteProfile(profile: EQProfile) {
        viewModelScope.launch {
            eqRepository.deleteProfile(profile)
        }
    }
    
    fun clearAllProfiles() {
        viewModelScope.launch {
            eqRepository.deleteAllProfiles()
        }
    }
}
