package com.voidlab.player.data.database

import androidx.room.*
import com.voidlab.player.data.models.EQProfile
import kotlinx.coroutines.flow.Flow

@Dao
interface EQProfileDao {
    @Query("SELECT * FROM eq_profiles ORDER BY updatedAt DESC")
    fun getAllProfiles(): Flow<List<EQProfile>>
    
    @Query("SELECT * FROM eq_profiles WHERE songId = :songId")
    suspend fun getProfileBySongId(songId: Long): EQProfile?
    
    @Query("SELECT * FROM eq_profiles WHERE songId = :songId")
    fun getProfileBySongIdFlow(songId: Long): Flow<EQProfile?>
    
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertProfile(profile: EQProfile)
    
    @Update
    suspend fun updateProfile(profile: EQProfile)
    
    @Delete
    suspend fun deleteProfile(profile: EQProfile)
    
    @Query("DELETE FROM eq_profiles")
    suspend fun deleteAllProfiles()
    
    @Query("SELECT COUNT(*) FROM eq_profiles")
    suspend fun getProfileCount(): Int
    
    @Query("SELECT * FROM eq_profiles WHERE isAutoGenerated = 1 AND learningProgress < 100")
    fun getLearningProfiles(): Flow<List<EQProfile>>
}
