package com.voidlab.player.audio.analysis

import com.voidlab.player.data.models.EQProfile
import kotlinx.coroutines.flow.StateFlow
import kotlin.math.abs

class AutoEQEngine(private val fftAnalyzer: FFTAnalyzer) {
    
    private val targetCurve = FloatArray(10) { 0f } // Ideal "flat" response
    private val learningHistory = mutableListOf<FloatArray>()
    private val maxHistorySize = 100 // ~30 seconds at 3 samples/sec
    
    fun startLearning() {
        learningHistory.clear()
    }
    
    fun captureSnapshot() {
        val currentSpectrum = fftAnalyzer.frequencySpectrum.value.copyOf()
        learningHistory.add(currentSpectrum)
        
        if (learningHistory.size > maxHistorySize) {
            learningHistory.removeAt(0)
        }
    }
    
    fun getLearningProgress(): Float {
        return (learningHistory.size.toFloat() / maxHistorySize * 100f).coerceAtMost(100f)
    }
    
    fun generateEQProfile(songId: Long, songTitle: String, songArtist: String): EQProfile {
        if (learningHistory.isEmpty()) {
            return EQProfile.fromBandValues(
                songId, songTitle, songArtist,
                FloatArray(10) { 0f },
                isAutoGenerated = true,
                learningProgress = 0f
            )
        }
        
        // Calculate average spectrum across all captured samples
        val averageSpectrum = FloatArray(10)
        for (sample in learningHistory) {
            for (i in sample.indices) {
                averageSpectrum[i] += sample[i]
            }
        }
        for (i in averageSpectrum.indices) {
            averageSpectrum[i] /= learningHistory.size
        }
        
        // Calculate EQ adjustments to flatten the curve
        val eqAdjustments = FloatArray(10)
        for (i in averageSpectrum.indices) {
            // Invert the spectrum to create compensating EQ
            val deviation = averageSpectrum[i] - targetCurve[i]
            eqAdjustments[i] = -deviation * 0.3f // Scale factor for gentle correction
            
            // Clamp to valid EQ range
            eqAdjustments[i] = eqAdjustments[i].coerceIn(-15f, 15f)
        }
        
        // Apply smoothing to avoid harsh EQ curves
        val smoothedEQ = smoothEQCurve(eqAdjustments)
        
        return EQProfile.fromBandValues(
            songId, songTitle, songArtist,
            smoothedEQ,
            isAutoGenerated = true,
            learningProgress = getLearningProgress()
        )
    }
    
    private fun smoothEQCurve(raw: FloatArray): FloatArray {
        val smoothed = FloatArray(raw.size)
        for (i in raw.indices) {
            when (i) {
                0 -> smoothed[i] = (raw[i] * 2 + raw[i + 1]) / 3f
                raw.size - 1 -> smoothed[i] = (raw[i - 1] + raw[i] * 2) / 3f
                else -> smoothed[i] = (raw[i - 1] + raw[i] * 2 + raw[i + 1]) / 4f
            }
        }
        return smoothed
    }
    
    fun reset() {
        learningHistory.clear()
    }
}
