package com.voidlab.player.data.models

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "eq_profiles")
data class EQProfile(
    @PrimaryKey val songId: Long,
    val songTitle: String,
    val songArtist: String,
    val band31Hz: Float = 0f,
    val band62Hz: Float = 0f,
    val band125Hz: Float = 0f,
    val band250Hz: Float = 0f,
    val band500Hz: Float = 0f,
    val band1kHz: Float = 0f,
    val band2kHz: Float = 0f,
    val band4kHz: Float = 0f,
    val band8kHz: Float = 0f,
    val band16kHz: Float = 0f,
    val isAutoGenerated: Boolean = true,
    val learningProgress: Float = 0f, // 0-100%
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
) {
    fun getBandValues(): FloatArray {
        return floatArrayOf(
            band31Hz, band62Hz, band125Hz, band250Hz, band500Hz,
            band1kHz, band2kHz, band4kHz, band8kHz, band16kHz
        )
    }
    
    companion object {
        const val MIN_GAIN = -15f
        const val MAX_GAIN = 15f
        
        fun fromBandValues(
            songId: Long,
            songTitle: String,
            songArtist: String,
            values: FloatArray,
            isAutoGenerated: Boolean = true,
            learningProgress: Float = 0f
        ): EQProfile {
            require(values.size == 10) { "Must provide exactly 10 band values" }
            return EQProfile(
                songId = songId,
                songTitle = songTitle,
                songArtist = songArtist,
                band31Hz = values[0],
                band62Hz = values[1],
                band125Hz = values[2],
                band250Hz = values[3],
                band500Hz = values[4],
                band1kHz = values[5],
                band2kHz = values[6],
                band4kHz = values[7],
                band8kHz = values[8],
                band16kHz = values[9],
                isAutoGenerated = isAutoGenerated,
                learningProgress = learningProgress
            )
        }
    }
}
